### ISSUE TITLE
Invalid config file

### ISSUE THREAD

**Issue by pkerpedjiev** [Caleydo/caleydo_vis_lineup#3]
Tried running:

`npm run test` 

And got the following error:

```
[pkerp@toc phovea_vis_lineup] [master]$ npm run test

> phovea_vis_lineup@0.0.1 pretest /Users/pkerp/projects/phovea_vis_lineup
> npm run compile


> phovea_vis_lineup@0.0.1 compile /Users/pkerp/projects/phovea_vis_lineup
> tsc


> phovea_vis_lineup@0.0.1 test /Users/pkerp/projects/phovea_vis_lineup
> karma start

13 11 2016 11:21:03.335:ERROR [config]: Invalid config file!
  SyntaxError: Unexpected token {
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:374:25)
    at Object.Module._extensions..js (module.js:405:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/Users/pkerp/projects/phovea_vis_lineup/karma.conf.js:7:17)
    at Module._compile (module.js:398:26)
    at Object.Module._extensions..js (module.js:405:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at Object.parseConfig (/Users/pkerp/projects/phovea_vis_lineup/node_modules/karma/lib/config.js:342:22)
    at new Server (/Users/pkerp/projects/phovea_vis_lineup/node_modules/karma/lib/server.js:56:20)
```

**Comment by sgratzl** [comment]
ensure node version >= 6

**Comment by pkerpedjiev** [comment]
That fixed it. Thanks!
